#!bin/bash

case $BANDIT_TARGET_ARCH in
    x86)
	URL=file:/srv/bandit/adobe/install_flash_player_11_linux.i386.tar.gz
	MD5=757d0835a038a1358d2e33ce7fb6c9eb
	ARCH=i386
	;;
    x86_64)
	URL=file:/srv/bandit/adobe/install_flash_player_11_linux.x86_64.tar.gz
	MD5=5bb834820d1563b2df2ed52fd9986b24
	ARCH=x86_64
	;;
esac

sources_prepare()
{
  bandit_source_rename install_flash_player_11_linux.$ARCH.tar.gz flash-player-11-NPAPI.tar.gz
  bandit_source_repackage_into flash-player-11-NPAPI.tar.gz flash-player-11-NPAPI
}

